export default [
  {
    id: 1,
    pseudo: 'BijouBelle',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'Bij@gmail.com',
    roles: ['ROLE_CREATOR'],
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Bijoux',
    }],
    slug: 'bijouxxx',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    firstname: 'Lola',
    lastname: 'Lilo',
    status: '',
    brand: 'Bijouxxx',
    phone: '0622853645',
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
    facebook: 'http://www.facebook.com',
    twitter: 'http://www.facebook.com',
    instagram: 'http://www.facebook.com',
    pinterest: 'http://www.facebook.com',
    linkedin: 'http://www.facebook.com',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [
      {
        id: 1,
        body: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, ma',
        publishedDate: '18/06/2021',
        user: {
          id: 2,
          pseudo: 'Crochetos',
          avatar: 'https://thispersondoesnotexist.com/image',
          mail: 'crochetos@gmail.com',
          category: 'Travaux d\'aiguille',
          slug: 'crochetos',
          firstName: 'Leeloo',
          lastName: 'DallasMultipass',
          status: '',
          brand: 'Crochetos',
          phone: '0622456985',
          description: 'blablablabla',
          facebook: 'http://www.facebook.com',
          twitter: '',
          instagram: '',
          pinterest: '',
          linkedin: '',
          website: 'http://www.facebook.com',
          pictures: [
            {
              id: 1,
              name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
            },
            {
              id: 2,
              name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
            },
            {
              id: 3,
              name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
            },
          ],
        },
      },
    ],
  },
  {
    id: 2,
    pseudo: 'Crochetos',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'crochetos@gmail.com',
    roles: ['ROLE_CREATOR'],
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Travaux d\'aiguille',
    }],
    slug: 'crochetos',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    firstname: 'Leeloo',
    lastname: 'DallasMultipass',
    status: '',
    brand: 'Crochetos',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: 'http://www.facebook.com',
    twitter: '',
    instagram: '',
    pinterest: '',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 3,
    pseudo: 'Claire',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'claire@gmail.com',
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Bijoux',
    }],
    roles: ['ROLE_CREATOR'],
    status: '',
    slug: 'claire',
    firstname: 'Claire',
    lastname: 'Dubis',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    brand: 'Clair\'s',
    phone: '0621569871',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: '',
    linkedin: 'http://www.facebook.com',
    website: '',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/5157293/pexels-photo-5157293.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 4,
    pseudo: 'Sophie',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'sophiegala@gmail.com',
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Sculpture',
    }],
    roles: ['ROLE_CREATOR'],
    status: '',
    slug: 'sophie-sculpture',
    firstname: 'sophie',
    lastname: 'Gala',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    brand: 'Sophie Sculpture',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: 'http://www.facebook.com',
    pinterest: '',
    linkedin: 'http://www.facebook.com',
    website: '',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/2491244/pexels-photo-2491244.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 5,
    pseudo: 'MarieCouture',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'mariecouture@gmail.com',
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Travaux d\'aiguille',
    }],
    roles: ['ROLE_CREATOR'],
    status: '',
    slug: 'marie-couture',
    firstname: 'Marie',
    lastname: 'Francis',
    brand: 'MarieCouture',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    phone: '0622456985',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: 'http://www.facebook.com',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/3771080/pexels-photo-3771080.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 6,
    pseudo: 'Maurice',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'maurice@gmail.com',
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Ebenisterie',
    }],
    roles: ['ROLE_CREATOR'],
    status: '',
    slug: 'maurice-bois',
    firstname: 'Maurice',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    lastname: 'Dupont',
    brand: 'Maurice Bois',
    phone: '0456315845',
    description: 'blablablabla',
    facebook: '',
    twitter: '',
    instagram: 'http://www.facebook.com',
    pinterest: '',
    linkedin: 'http://www.facebook.com',
    website: '',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/5466151/pexels-photo-5466151.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 7,
    pseudo: 'Germaine',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'germaine@gmail.com',
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Peinture',
    }],
    roles: ['ROLE_CREATOR'],
    status: '',
    slug: 'germaine-frechette',
    firstname: 'Germaine',
    lastname: 'Fréchette',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    brand: 'Peinture Fraîche',
    phone: '0192939226',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: 'http://www.facebook.com',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/1570779/pexels-photo-1570779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
  {
    id: 8,
    pseudo: 'Germaine',
    avatar: 'https://thispersondoesnotexist.com/image',
    email: 'germaine@gmail.com',
    category: [{
      description: '',
      photo: '',
      slug: '',
      category_name: 'Peinture',
    }],
    slug: 'germaine-frechette',
    roles: ['ROLE_CREATOR'],
    status: '',
    firstname: 'Germaine',
    lastname: 'Fréchette',
    brand: 'Peinture Fraîche',
    logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    phone: '0192939226',
    description: 'blablablabla',
    facebook: '',
    twitter: 'http://www.facebook.com',
    instagram: '',
    pinterest: 'http://www.facebook.com',
    linkedin: '',
    website: 'http://www.facebook.com',
    pictures: [
      {
        id: 1,
        name: 'https://images.pexels.com/photos/1570779/pexels-photo-1570779.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 2,
        name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
      {
        id: 3,
        name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      },
    ],
    comments: [],
  },
];

export const categories = [
  {
    id: 1,
    category_name: 'Travaux d\'aiguille',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'travaux-aiguille',
    photo: 'https://images.pexels.com/photos/37631/sewing-thimble-pins-safety-pins-37631.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    users: [
      {
        id: 2,
        pseudo: 'Crochetos',
        avatar: 'https://thispersondoesnotexist.com/image',
        email: 'crochetos@gmail.com',
        roles: ['ROLE_CREATOR'],
        category: {
          description: '',
          photo: '',
          slug: '',
          category_name: 'Travaux d\'aiguille',
        },
        slug: 'crochetos',
        logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        firstname: 'Leeloo',
        lastname: 'DallasMultipass',
        status: '',
        brand: 'Crochetos',
        phone: '0622456985',
        description: 'blablablabla',
        facebook: 'http://www.facebook.com',
        twitter: '',
        instagram: '',
        pinterest: '',
        linkedin: '',
        website: 'http://www.facebook.com',
        pictures: [
          {
            id: 1,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
        comments: [],
      },
      {
        id: 5,
        pseudo: 'MarieCouture',
        avatar: 'https://thispersondoesnotexist.com/image',
        email: 'mariecouture@gmail.com',
        category: {
          description: '',
          photo: '',
          slug: '',
          category_name: 'Travaux d\'aiguille',
        },
        roles: ['ROLE_CREATOR'],
        status: '',
        slug: 'marie-couture',
        firstname: 'Marie',
        lastname: 'Francis',
        brand: 'MarieCouture',
        logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        phone: '0622456985',
        description: 'blablablabla',
        facebook: '',
        twitter: 'http://www.facebook.com',
        instagram: '',
        pinterest: 'http://www.facebook.com',
        linkedin: '',
        website: 'http://www.facebook.com',
        pictures: [
          {
            id: 1,
            name: 'https://images.pexels.com/photos/3771080/pexels-photo-3771080.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
        comments: [],
      },
    ],
  },
  {
    id: 2,
    category_name: 'Bijoux',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'bijoux',
    photo: 'https://images.pexels.com/photos/5157363/pexels-photo-5157363.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    users: [
      {
        id: 1,
        pseudo: 'BijouBelle',
        avatar: 'https://thispersondoesnotexist.com/image',
        email: 'Bij@gmail.com',
        roles: ['ROLE_CREATOR'],
        category: {
          description: '',
          photo: '',
          slug: '',
          category_name: 'Bijoux',
        },
        slug: 'bijouxxx',
        logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        firstname: 'Lola',
        lastname: 'Lilo',
        status: '',
        brand: 'Bijouxxx',
        phone: '0622853645',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
        facebook: 'http://www.facebook.com',
        twitter: 'http://www.facebook.com',
        instagram: 'http://www.facebook.com',
        pinterest: 'http://www.facebook.com',
        linkedin: 'http://www.facebook.com',
        website: 'http://www.facebook.com',
        pictures: [
          {
            id: 1,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
        comments: [
          {
            id: 1,
            body: 'Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l\'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte. Il n\'a pas fait que survivre cinq siècles, ma',
            publishedDate: '18/06/2021',
            user: {
              id: 2,
              pseudo: 'Crochetos',
              avatar: 'https://thispersondoesnotexist.com/image',
              mail: 'crochetos@gmail.com',
              category: 'Travaux d\'aiguille',
              slug: 'crochetos',
              firstName: 'Leeloo',
              lastName: 'DallasMultipass',
              status: '',
              brand: 'Crochetos',
              phone: '0622456985',
              description: 'blablablabla',
              facebook: 'http://www.facebook.com',
              twitter: '',
              instagram: '',
              pinterest: '',
              linkedin: '',
              website: 'http://www.facebook.com',
              pictures: [
                {
                  id: 1,
                  name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
                },
                {
                  id: 2,
                  name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
                },
                {
                  id: 3,
                  name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
                },
              ],
            },
          },
        ],
      },
      {
        id: 3,
        pseudo: 'Claire',
        avatar: 'https://thispersondoesnotexist.com/image',
        email: 'claire@gmail.com',
        category: {
          description: '',
          photo: '',
          slug: '',
          category_name: 'Bijoux',
        },
        roles: ['ROLE_CREATOR'],
        status: '',
        slug: 'claire',
        firstname: 'Claire',
        lastname: 'Dubis',
        logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        brand: 'Clair\'s',
        phone: '0621569871',
        description: 'blablablabla',
        facebook: '',
        twitter: 'http://www.facebook.com',
        instagram: '',
        pinterest: '',
        linkedin: 'http://www.facebook.com',
        website: '',
        pictures: [
          {
            id: 1,
            name: 'https://images.pexels.com/photos/5157293/pexels-photo-5157293.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
        comments: [],
      },
    ],
  },
  {
    id: 3,
    category_name: 'Sculpture',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'sculpture',
    photo: 'https://images.pexels.com/photos/6598660/pexels-photo-6598660.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    users: [
      {
        id: 4,
        pseudo: 'Sophie',
        avatar: 'https://thispersondoesnotexist.com/image',
        email: 'sophiegala@gmail.com',
        category: {
          description: '',
          photo: '',
          slug: '',
          category_name: 'Sculpture',
        },
        roles: ['ROLE_CREATOR'],
        status: '',
        slug: 'sophie-sculpture',
        firstname: 'sophie',
        lastname: 'Gala',
        logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        brand: 'Sophie Sculpture',
        phone: '0622456985',
        description: 'blablablabla',
        facebook: '',
        twitter: '',
        instagram: 'http://www.facebook.com',
        pinterest: '',
        linkedin: 'http://www.facebook.com',
        website: '',
        pictures: [
          {
            id: 1,
            name: 'https://images.pexels.com/photos/2491244/pexels-photo-2491244.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
          },
          {
            id: 2,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
        comments: [],
      },
    ],
  },
  {
    id: 4,
    category_name: 'Ebénisterie',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'ebenisterie',
    photo: 'https://images.pexels.com/photos/5466161/pexels-photo-5466161.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    users: [
      {
        id: 6,
        pseudo: 'Maurice',
        avatar: 'https://thispersondoesnotexist.com/image',
        email: 'maurice@gmail.com',
        category: {
          description: '',
          photo: '',
          slug: '',
          category_name: 'Ebenisterie',
        },
        roles: ['ROLE_CREATOR'],
        status: '',
        slug: 'maurice-bois',
        firstname: 'Maurice',
        logo: 'https://images.pexels.com/photos/1337388/pexels-photo-1337388.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
        lastname: 'Dupont',
        brand: 'Maurice Bois',
        phone: '0456315845',
        description: 'blablablabla',
        facebook: '',
        twitter: '',
        instagram: 'http://www.facebook.com',
        pinterest: '',
        linkedin: 'http://www.facebook.com',
        website: '',
        pictures: [
          {
            id: 1,
            name: 'https://images.pexels.com/photos/5466151/pexels-photo-5466151.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 2,
            name: 'https://images.pexels.com/photos/4544816/pexels-photo-4544816.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
          {
            id: 3,
            name: 'https://images.pexels.com/photos/2767689/pexels-photo-2767689.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
          },
        ],
        comments: [],
      },
    ],
  },
  {
    id: 5,
    category_name: 'Design textile',
    description: 'Travaux de couture décorative et l\'artisanat des arts textiles : tricot, crochet, dentelle, feutrage, broderie, points noués etc...',
    slug: 'design-textile',
    photo: 'https://images.pexels.com/photos/365067/pexels-photo-365067.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    users: [],
  },
];

export const comments = [
  {
    id: 1,
    body: 'Super top ce créateur',
    publishedDate: '18/06/2021',
  },
];
